In [51]:
import pandas as pd
import numpy as np


In [52]:
df = pd.read_csv("data/raw/e-shop clothing 2008.csv", sep=";")
print(df.head(5))

   year  month  day  order  country  session ID  page 1 (main category)  \
0  2008      4    1      1       29           1                       1   
1  2008      4    1      2       29           1                       1   
2  2008      4    1      3       29           1                       2   
3  2008      4    1      4       29           1                       2   
4  2008      4    1      5       29           1                       2   

  page 2 (clothing model)  colour  location  model photography  price  \
0                     A13       1         5                  1     28   
1                     A16       1         6                  1     33   
2                      B4      10         2                  1     52   
3                     B17       6         6                  2     38   
4                      B8       4         3                  2     52   

   price 2  page  
0        2     1  
1        2     1  
2        1     1  
3        2     1  
4        1     

In [53]:
df['model photography'].astype(int).unique()

array([1, 2])

In [54]:
df['price 2'].unique()

array([2, 1])

In [72]:
df['page'].unique()

array([1, 4, 5, 2, 3])

In [55]:
# rename price 2 to higher_than_average, 1 as True, 2 as false
df['higher_than_average'] = df['price 2'].map({1: 1, 2: 0})
print(df['higher_than_average'].unique())
df.drop(columns=['price 2'], inplace=True)
print(df.head(5))

[0 1]
   year  month  day  order  country  session ID  page 1 (main category)  \
0  2008      4    1      1       29           1                       1   
1  2008      4    1      2       29           1                       1   
2  2008      4    1      3       29           1                       2   
3  2008      4    1      4       29           1                       2   
4  2008      4    1      5       29           1                       2   

  page 2 (clothing model)  colour  location  model photography  price  page  \
0                     A13       1         5                  1     28     1   
1                     A16       1         6                  1     33     1   
2                      B4      10         2                  1     52     1   
3                     B17       6         6                  2     38     1   
4                      B8       4         3                  2     52     1   

   higher_than_average  
0                    0  
1                 

In [56]:
df['model photography'] = df['model photography'].map({1: "en face", 2: "profile"})
df['model photography'].head(5)

0    en face
1    en face
2    en face
3    profile
4    profile
Name: model photography, dtype: str

In [57]:
df['location'].unique()
df['location'] = df['location'].map(id_to_position)
df['location'].head(5)

0    bottom in the middle
1            bottom right
2       top in the middle
3            bottom right
4               top right
Name: location, dtype: str

In [58]:
id_to_position = {
    1: "top left",
    2: "top in the middle",
    3: "top right",
    4: "bottom left",
    5: "bottom in the middle",
    6: "bottom right"
}


In [59]:
df['colour'] = df['colour'].map(id_to_color)
df['colour'].head()

0    beige
1    beige
2    olive
3     gray
4    brown
Name: colour, dtype: str

In [60]:
id_to_color = {
    1: "beige",
    2: "black",
    3: "blue",
    4: "brown",
    5: "burgundy",
    6: "gray",
    7: "green",
    8: "navy blue",
    9: "of many colors",
    10: "olive",
    11: "pink",
    12: "red",
    13: "violet",
    14: "white"
}


In [61]:
df['page 2 (clothing model)'].unique()

<StringArray>
['A13', 'A16',  'B4', 'B17',  'B8', 'C56', 'C57', 'P67', 'P82', 'B31',
 ...
 'P27', 'P24', 'A43', 'P31', 'P53', 'P45', 'P54', 'P28', 'P22', 'P79']
Length: 217, dtype: str

In [62]:
# page 1 (main category) mapping
df['page 1 (main category)'].unique()
df['main_category'] = df['page 1 (main category)'].map(id_to_category)
df.drop(columns = ['page 1 (main category)'], inplace = True)
df.head()


,year,month,day,order,country,session ID,page 2 (clothing model),colour,location,model photography,price,page,higher_than_average,main_category
0,2008,4,1,1,29,1,A13,beige,bottom in the middle,en face,28,1,0,trousers
1,2008,4,1,2,29,1,A16,beige,bottom right,en face,33,1,0,trousers
2,2008,4,1,3,29,1,B4,olive,top in the middle,en face,52,1,1,skirts
3,2008,4,1,4,29,1,B17,gray,bottom right,profile,38,1,0,skirts
4,2008,4,1,5,29,1,B8,brown,top right,profile,52,1,1,skirts


In [63]:
id_to_category = {
    1: "trousers",
    2: "skirts",
    3: "blouses",
    4: "sale"
}


In [64]:
df['session ID'].unique()
df['session ID'].astype(int)

0             1
1             1
2             1
3             1
4             1
          ...  
165469    24024
165470    24025
165471    24026
165472    24026
165473    24026
Name: session ID, Length: 165474, dtype: int64

In [65]:

df['order'].astype(int)
df['order'].head(5)

0    1
1    2
2    3
3    4
4    5
Name: order, dtype: int64

In [66]:
id_to_country = {
    1: "Australia",
    2: "Austria",
    3: "Belgium",
    4: "British Virgin Islands",
    5: "Cayman Islands",
    6: "Christmas Island",
    7: "Croatia",
    8: "Cyprus",
    9: "Czech Republic",
    10: "Denmark",
    11: "Estonia",
    12: "unidentified",
    13: "Faroe Islands",
    14: "Finland",
    15: "France",
    16: "Germany",
    17: "Greece",
    18: "Hungary",
    19: "Iceland",
    20: "India",
    21: "Ireland",
    22: "Italy",
    23: "Latvia",
    24: "Lithuania",
    25: "Luxembourg",
    26: "Mexico",
    27: "Netherlands",
    28: "Norway",
    29: "Poland",
    30: "Portugal",
    31: "Romania",
    32: "Russia",
    33: "San Marino",
    34: "Slovakia",
    35: "Slovenia",
    36: "Spain",
    37: "Sweden",
    38: "Switzerland",
    39: "Ukraine",
    40: "United Arab Emirates",
    41: "United Kingdom",
    42: "USA",
    43: "biz (*.biz)",
    44: "com (*.com)",
    45: "int (*.int)",
    46: "net (*.net)",
    47: "org (*.org)"
}


In [67]:
df['country'].nunique()
# map the country column to actual country names
df['country'] = df['country'].map(id_to_country)
print(df['country'].unique())

<StringArray>
[                'Poland',                'Ireland',         'Czech Republic',
                'Germany',            'Switzerland',              'Lithuania',
         'United Kingdom',           'unidentified',                'Romania',
            'com (*.com)',               'Slovakia',                 'Norway',
            'net (*.net)',                 'France',                'Denmark',
            'Netherlands',                'Croatia',             'Luxembourg',
                  'India',                 'Greece',                  'Italy',
                'Iceland',                    'USA',                 'Cyprus',
                'Belgium',                 'Sweden',               'Portugal',
                'Finland',            'biz (*.biz)',                 'Latvia',
            'org (*.org)',                  'Spain',                'Austria',
             'San Marino',                 'Russia',            'int (*.int)',
                'Hungary',            

In [68]:
# create one hot encoding for the country column
df = pd.get_dummies(df, columns=['country'])
print(df.head(5))

   year  month  day  order  session ID page 2 (clothing model) colour  \
0  2008      4    1      1           1                     A13  beige   
1  2008      4    1      2           1                     A16  beige   
2  2008      4    1      3           1                      B4  olive   
3  2008      4    1      4           1                     B17   gray   
4  2008      4    1      5           1                      B8  brown   

               location model photography  price  ...  country_USA  \
0  bottom in the middle           en face     28  ...        False   
1          bottom right           en face     33  ...        False   
2     top in the middle           en face     52  ...        False   
3          bottom right           profile     38  ...        False   
4             top right           profile     52  ...        False   

   country_Ukraine country_United Arab Emirates  country_United Kingdom  \
0            False                        False                  

In [69]:
df['year'].nunique()
df.drop(columns=['year'], inplace=True)

In [70]:
df['month'].unique()
df['month'].astype(int)

0         4
1         4
2         4
3         4
4         4
         ..
165469    8
165470    8
165471    8
165472    8
165473    8
Name: month, Length: 165474, dtype: int64

In [71]:
df['day'].unique()
df['day'].astype(int)

0          1
1          1
2          1
3          1
4          1
          ..
165469    13
165470    13
165471    13
165472    13
165473    13
Name: day, Length: 165474, dtype: int64